services:
  - docker

script:
  - docker build -t inseefrlab/inspacy .

deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push inseefrlab/inspacy
  on:
    branch: master
env:
  global:
  - secure YuNegA8Byh0ns79nDJPJxCTTLwAK2i4F0oS3xC4r9AxtgAzmyhB0S0ADRtaanpFmbx0ljQym0KyAN1SmoYES9OrAh1fIERgtfO82v/JLaCvAOt+IrPjokFoeemw6z9RvmqnkxRcOYE0GjwZOEEizgpaH0FMW5oNaTW6JCuKA4AhHNlSNuczk8/KX3bf07gXDyliueetcO9GinbQjocf80nPIQUTsa0Id/hxxgR68im6xOjaWEdR+k3G0Pu7zeVhypjP3+wCgUGkJxZmfIxjLYA0pOaTwonGjdEd1klXD2/veuWO3fSp69Qv1uXtxhvJV1LnO7GWVX9lai/zkxu7AQhtg/ntkitNBfnl/CEyON38wwOCBZM4SbkX5UNK3qkoRlBvrP1h9ZhK9V2oq1ir3i8T6o/U64IDiLBuBGePlzL8kHFE2HH4umZ+xFdQvwHO6zzps9EdEj8781YX3/h0BfQMzcLgxkzSrktA4banIVRDT2XoxUNjE1D7cenXRVcctdcL1PyqAl2WbOScNjw5ylbWgQkW5L0679FMSW+i0ET/zjDkUmizI19VCMAtM7HKsZbYWMR6Q63hVsBt1R6X0dNt/kZIiLQyTAZmXy5u36FnknaaWg+EYm+HW8vf3iG3dG0TDv/DiFuhVe971cg/Cq7bUKcNuXT6v5nPSvnY7aUY=
  - secure zIYU02dLI0xr9TvvFbYlY491tXsCJ5yreTZ0aPBhZwPOlsU5Dmv3V2n1HBs2RYvrF3Iq1zSjhOHJnLgZSMVt2q8ZBl5bRVhn5RVfDcCtK80APTrkhQxQ7R1VC+R+dygNJqwgEL6vGngMEmNex4yjdTCM9fNwoy/0jUebAO5PbQcnKAuK50G17jlsJRKQRZ7+qMVsC1SOZJhm5BVAeLlS0t3iApY6m1zzVNXxB4xzWl71WqC7OF14p+lNpVLxHVXYMVGAG5oFo+efre9hCwpFYOrEsS7SSLx4F3cg9Hy1eCGnsswN8JpYBYZgYNJkrTqnm6XzDl2kOGqOCI9lRdpMUpddGtGZFyp6i/512/+0pu+wM6BBoQUec4MtbW1Oy2x86znE323d0KYCym/6SYKOR1ktPXECl4T8/FKYUx3IeAcIQ3Sz5Mr3uJRR+T1P5ns2BHO9Jf5HYIySh3zQpU+wo9bHZoQ3LTzDTdjYG7ZvwahSFvr3QOTK3SrzmZJ3oYfZxPdQ2HNQ3E+HbaFw16FG2wEobJSAUnVXN6sfpPa/1E4NEeQ6ujr1zaLrBd+TdpDB9Ik4P4VP5iteHgOWM5IzLbQdlv0tvVZSP/Ih2QGIzTVJlJh57BlsvWc/V+i4wbDOPiTCPNVwfdvH8A/s4lqt6a7q+sKBkrzMIHjZ9TfcCFA=